### ISSUE TITLE
wait for not present and not displayed

### ISSUE THREAD

**Issue by kahan002** [hetznercloud/protractor-test-helper#17]
If there is an error because by the time someone called wait to be not present or displayed, the element already got to be not present (this happened to me running headless), there are 2 potential issues. One is that in this case it would be more logical to return true (because the thing is not present or displayed, even though one might say the function needs to know that it once was), rather than false as they do in the error handling function at the very end.
But in that case, I also seem to be getting "Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.", which says to me that perhaps try..catch is needed within the function.
And I see an error that I caught saying waitfortoast Role Worker added to user User, OrgtwoTimeoutError: Element by.cssContainingText(".toast-success", "Role Worker added to user User, Orgtwo") is not present
Wait timed out after 10033ms, though that may be from when I was waiting for the message to appear rather than disappear.
My code was://it was formatted
```
var waitForTextOfToastSuccessToComeAndGo = async function(keySentence:string){
  try{
    await waitToBePresent(by.cssContainingText('.toast-success',keySentence), 10000);
    await waitToBeNotPresent(by.cssContainingText('.toast-success',keySentence), 10000);
    return;
  }catch(e){flowLog('waitfortoast '+keySentence+e); return;}
}
```
The library has been very useful, and I appreciate what you have done with it. I am also open to the possibility that I am speculating here and may be making an issue where the code is working as designed.

**Comment by wachri** [comment]
Thank you for using the lib and opening a ticket :).

With the behavior in the error case of the  `waitToBeNotPresent` and `waitToBeNotDisplayed` I think you are are right and it's a bug and we should return `true`, but I need to investigate it a bit more.

For the second point I'm not 100% sure that I got your point right. The problem you see is, that when you run into a timeout the `Promise` returned e.g. from `waitToBePresent` rejects and that is not handle? Don't know if a try/catch would solve the problem, because normally you would like the test to fail and with a catched rejection you only get a log message (in your example), with out a fail. Locally you maybe see the log but when you run the tests in the CI you think everything is ok because of the missing exit code. 

Do you have more experience with that or an idea how to solve this?

**Comment by kahan002** [comment]
And this library is really helpful. I switched my .clicks over to your click(), and I got much greater clarity that the reason I'm not seeing the toast success message is that the button I thought I was clicking on to get it was not there (which is a bug, I think, but in our product). The error message Click error: TimeoutError: Element By(css selector, button[title="Add role to user"]) is not present nor displayed was enlightening.

**Comment by kahan002** [comment]
The error I was seeing was indeed of my own making. I still do believe that in an ideal world that when things are supposed to be not displayed or present, it should not be a false if one cannot find them in the first place.

**Comment by wachri** [comment]
We got a bit deeper into the topic and I discussed it with the team. In the `waitToBeNotPresent ` and the `waitToBeNotDisplayed` we use the `isPresent` function. `isPresent` is designed to check the presence of an element and it shouldn't throw an error if the element doesn't exist. In every normal scenario there should no error here. We think when it get's rejected we should not catch the error and remove the handler for this, so you get a proper error message and you can fix the error.

@kahan002 Is this something you can live with?

**Comment by kahan002** [comment]
Yes. Thanks for thinking it through.
